### ISSUE TITLE
Cannot assign a custom IP with internal LB type service 

### ISSUE THREAD

**Issue by bigmyx** [kubernetes/community#1573]
@kubernetes/sig-azure-bugs

Hello,
 
It seems like Azure K8s does not create a custom custom ingress IP address as defined:

```
---
apiVersion: v1
kind: Service
metadata:
  name: test
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  ports:
  - port: 514
    protocol: UDP
  selector:
    component: test
    role: test
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 10.0.73.253
```

Even though, I specified  `10.0.73.253` as ingress IP, other (`10.0.73.204`) IP is assigned: 

```
$ kubectl describe svc test
Name:                     test
Namespace:                default
Labels:                   <none>
Annotations:              service.beta.kubernetes.io/azure-load-balancer-internal=true
Selector:                 component=test,role=test
Type:                     LoadBalancer
IP:                       10.0.144.243
LoadBalancer Ingress:     10.0.73.204
Port:                     <unset>  514/UDP
TargetPort:               514/UDP
NodePort:                 <unset>  32698/UDP
Endpoints:                172.16.193.68:514,172.16.193.69:514
Session Affinity:         None
External Traffic Policy:  Cluster
Events:
  Type    Reason                Age   From                Message
  ----    ------                ----  ----                -------
  Normal  EnsuringLoadBalancer  9m    service-controller  Ensuring load balancer
  Normal  EnsuredLoadBalancer   8m    service-controller  Ensured load balancer
```

Additional info: 

The cluster is connected to custom VNET/Subnet. 

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.3", GitCommit:"f0efb3cb883751c5ffdbe6d515f3cb4fbe7b7acd", GitTreeState:"clean", BuildDate:"2017-11-09T07:27:47Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.2", GitCommit:"bdaeafa71f6c7c04636251031f93464384d54963", GitTreeState:"clean", BuildDate:"2017-10-24T19:38:10Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```

Can anyone please advise?
