### ISSUE TITLE
Proposal: Use Selector Generation for Deployments, ReplicaSet, DaemonSet, StatefulSet and ReplicationController

### ISSUE THREAD

**Issue by mengqiy** [kubernetes/community#187]
Selector Generation for Deployments, ReplicaSet, DaemonSet, StatefulSet and ReplicationController
=============

# Goals
Make selector easy to use and less error-prone for Deployments, ReplicaSet, DaemonSet, StatefulSet and ReplicationController. Make `kubectl apply` work with selector.

# Problem Description
The field `spec.selector` of Deployments, ReplicaSet, DaemonSet are default to `spec.template.metadata.labels`, if it is unspecified.
And there is validation to make sure `spec.selector` always selects the pod template.
The defaulting of selector may prevent from `kubectl apply` from working when updating the `spec.selector` field.

# Example
Here is an example from https://github.com/kubernetes/kubernetes/issues/26202#issuecomment-221421254 showing how defaulting selector prevents `kubectl apply` from working.
First create a Deployment via `kubectl apply`
```yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: nginx
        test: abcd
    spec:
      containers:
      - name: nginx
        image: nginx:1.7.9
        ports:
        - containerPort: 80
```
Then remove any of the labels in the file (and optionally specify the selector), and then `kubectl apply`.
```yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 3
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.7.9
        ports:
        - containerPort: 80
```
Error message is like
```
The Deployment "nginx-deployment" is invalid: spec.template.metadata.labels: Invalid value: {"app":"nginx"}: `selector` does not match template `labels`
```
`kubectl apply` won't suffer this issue, if selector generation is also used for Deployments, ReplicaSet, DaemonSet, StatefulSet and ReplicationController.

# Proposed changes

The [Selector Generation](https://github.com/kubernetes/community/blob/master/contributors/design-proposals/selector-generation.md) works well in Job. Use this pattern for Deployments, ReplicaSet, DaemonSet, StatefulSet and ReplicationController.
If `spec.selector` is not derived from `spec.template.metadata.labels`, `kubectl apply` will works well for selectors.

## API

The change will be the same as [the changes to Job](https://github.com/kubernetes/kubernetes/blob/master/docs/design/selector-generation.md#api).
And the changes will be applied to Deployments, ReplicaSet, DaemonSet, StatefulSet and ReplicationController.
Deployments, ReplicaSet, DaemonSet, StatefulSet are in `extensions/v1beta1`.
ReplicationController is in `core/v1`.

## kubectl

No required changes.

## Version skew

1) old client vs new APIserver: old client don't know field `spec.manualSelector`, it will be considered as nil value at server-side and the server will auto-generate selector. 

2) new client vs old APIserver: `spec.manualSelector` will be ignored, since the APIServer don't understand this field. It should behave as before.

cc: @kubernetes/sig-api-machinery @kubernetes/sig-cli @kubernetes/sig-apps

Will send a PR for proposal after get some feedback.
