### ISSUE TITLE
[bug] Stateful Set: Dynamic Provisioning of PV/PVC

### ISSUE THREAD

**Issue by carlolm** [kubernetes/community#1948]
## Objective
Create pods with persistent volumes to store large amounts of data that is regularly synced.  The data should persist even if the other modules of the pod are changed or updated.  If a persistent volume is made inactive (for example, scaling down or when restarting the stateful set), when it is re-mounted again by another/new pod, data syncing should resume from when the persistent was previously made inactive; i.e. data should be retained.

## Current behavior
After the persistent volume is disconnected, when resuming, data is reset and syncing starts as if the the persistent volume is empty.

## How to reproduce:
1. Create the stateful set as below
2. Check the logs of the `event-watcher` container of the "parity set"

```
$ kubectl logs parity-set-1 -c event-watcher --namespace parity-rp

# Example log:
getBlockNumber:
 => 103482
```

This number displayed under getBlockNumber is the currently synced block.
If the persistent volume works as intended, this number should resume from approximately where it was when the pod is disconnected.  If it starts again at `0` upon restarting of the pod/PV connection, it means that the data from the previous sync has not persisted.

3. Restart pods: either by scaling to 1 and scaling back up to 2 (checking `parity-set-1`) or by deleting the stateful set and re-creating (can check both pods)

```
apiVersion: v1
kind: Namespace
metadata:
  name: parity-rp
  labels:
    name: parity-rp
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: parity-config
  namespace: parity-rp
data:
  config.toml: |-
    [parity]
    mode = "active"
    mode_timeout = 300
    mode_alarm = 3600
    auto_update = "critical"
    release_track = "stable"
    public_node = false
    no_download = false
    no_consensus = false
    base_path = "/parity-data"
    db_path = "/parity-data/chains"
    keys_path = "/parity-data/keys"
    chain = "ropsten"

    [ui]
    disable = true

    [rpc]
    disable = false
    port = 8545
    interface = "0.0.0.0"
    cors = "null"
    apis = ["web3", "eth", "net"]
    hosts = ["all"]
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: parity-ssd
  namespace: parity-rp
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-ssd
  zones: us-west1-a
reclaimPolicy: Retain
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: parity-set
  namespace: parity-rp
  labels:
    app: parity-set
spec:
  replicas: 2
  selector:
    matchLabels:
      app: parity-set
  serviceName: parity-set
  template:
    metadata:
      name: parity-set
      labels:
        app: parity-set
    spec:
      containers:
        - name: parity
          image: "parity/parity:stable-release"
          imagePullPolicy: IfNotPresent
          command: ["/parity/parity"]
          args: ["--config", "/config/config.toml"]
          ports:
            - containerPort: 8545
              protocol: TCP
              name: rcp-port
          livenessProbe:
            tcpSocket:
              port: 8545
            initialDelaySeconds: 60
          volumeMounts:
            - name: parity-config
              mountPath: /config
              readOnly: true
            - name: parity-data
              mountPath: /parity-data
        - name: event-watcher
          # TEMPORARY TEST IMAGE
          image: "yzhang1994/eth-node-checker"
          imagePullPolicy: IfNotPresent
          command: ["npm"]
          args: ["start"]
          env:
            - name: "WEB3_URL"
              value: "http://localhost:8545"
      volumes:
      - name: parity-config
        configMap:
          name: parity-config
  volumeClaimTemplates:
  - metadata:
      name: parity-data
      namespace: parity-rp
    spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: "parity-ssd"
      resources:
        requests:
          storage: 200Gi
```
