### ISSUE TITLE
Misbehavior in ClusterRole with aggregation rule

### ISSUE THREAD

**Issue by JackWindows** [kubernetes/community#2858]
I have the following ClusterRole with aggregation rule
```
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kubernetes-dashboard-viewer
aggregationRule:
  clusterRoleSelectors:
  # Inherit default view rules
  - matchLabels:
      kubernetes.io/bootstrapping: rbac-defaults
      rbac.authorization.k8s.io/aggregate-to-view: "true"
  - matchLabels:
      # Inherit additional rules
      kubernetes-dashboard-viewer-additional-rules: "true"
  - matchExpressions:
    - key: name
      operator: In
      values: ["view"]
rules: [] # Rules are automatically filled in by the controller manager.
```
Note the 3rd clusterRoleSelectors "matchExpressions" is wrong, but it shouldn't affect how the 1st and 2nd selectors work. However, it turns out the 3rd malformed clusterRoleSelector will prevent rules from `system:aggregate-to-view` (which matches the 2nd clusterRoleSelector) being added to the created cluster role.
If I remove the 3rd clusterRoleSelector then the created cluster role has both set of rules from 1st and 2nd clusterRoleSelectors.

Slack thread https://kubernetes.slack.com/archives/C09NXKJKA/p1540513141000100
