### ISSUE TITLE
MountVolume.SetUp failed for volume “mongo-two”: lstat /mongo/data: no such file or directory

### ISSUE THREAD

**Issue by slimee** [kubernetes/community#3020]
**What happened**:
Failed to mount a local-storage volume. (stateful-set with PVC + PV + local-storage class)
First PV is at "Bound" status with correct PVC, but deployment never ends.
Kubelet log say:  lstat /mongo/data: no such file or directory
But /mongo/data exists on the hosts.

**What you expected to happen**:
Volume should be successfully mounted.

**How to reproduce it (as minimally and precisely as possible)**:
Create storage class:
```
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: local-storage
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Retain
```

Create 3 PVs:
```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-[one/two/three]
spec:
  capacity:
    storage: 40Gi
  accessModes:
  - ReadWriteOnce
  storageClassName: local-storage
  local:
    path: /mongo/data
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - [one/two/three]
```

Create a stateful-set with 3 replicas and a PVC: (mongo-replicaset helm chart 3.8.0)
```
...
  volumeMounts:
    - mountPath: /data/db
      name: datadir
...
  volumeClaimTemplates:
  - metadata:
      creationTimestamp: null
      name: datadir
    spec:
      accessModes:
      - ReadWriteOnce
      storageClassName: local-storage
      resources:
        requests:
          storage: 40Gi
...
```

**Anything else we need to know?**:
My hosts don't have the lstat command.

**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.5", GitCommit:"32ac1c9073b132b8ba18aa830f46b77dcceb0723", GitTreeState:"clean", BuildDate:"2018-06-21T11:46:00Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.5", GitCommit:"753b2dbc622f5cc417845f0ff8a77f539a4213ea", GitTreeState:"clean", BuildDate:"2018-11-26T14:31:35Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration: Virtual Private Servers. 2vCore, 8Gb, 80Gb
- OS (e.g. from /etc/os-release): Ubuntu 16.04.5 LTS
- Kernel (e.g. `uname -a`): Linux vps617733 4.4.0-140-generic
- Install tools: Kubernetes installed via Rancher v2.1.3, helm v2.10.0-rancher5

Thanks you very much
