### ISSUE TITLE
Add Support to Deny RBAC Rules

### ISSUE THREAD

**Issue by t0rr3sp3dr0** [kubernetes/community#4061]
The absence of denial rules in K8s makes it difficult or impracticable to restrict access while being permissive.

Some use cases would be:
- Allow user to perform all actions that do not involve `kube-system` namespace. Including being able to create new namespaces and automatically have access granted to perform actions on it.
- Prevent secrets from being accessed by some subject in a namespace and have access to custom resources without having to list all of them manually.

We could have something like this:
```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: ns
  name: role
rules:
  - kind: Allow
    apiGroups:
      - ''
      - apps
      - extensions
    resources:
      - '*'
    verbs:
      - '*'
  - kind: Deny
    apiGroups:
      - ''
    resources:
      - 'secrets'
    verbs:
      - 'get'
      - 'watch'
      - 'list'
```

To preserve backwards compatibility, `kind` could be set to `Allow` by default.
