### ISSUE TITLE
How does an external application access the k8s headless service?

### ISSUE THREAD

**Issue by zxgm** [kubernetes/community#4610]
How does an external application access the k8s headless service? For example, the external access port is 31111. How is the service.yaml written?
```
apiVersion: v1
kind: Service
metadata:
  name: gateway
  namespace: ai
  labels:
    name: gateway
spec:
  type: NodePort
  clusterIP: None
  ports:
  - name: gateway
    port: 11111
    targetPort: 11111
    nodePort:31111
  selector:
    name: gateway
```

Is that correctly?
