### ISSUE TITLE
Limitrange request causes indefinite amount of pods spawned

### ISSUE THREAD

**Issue by dza89** [kubernetes/community#5011]
Kubernetes version: 1.16
kubeletVersion: v1.16.13-eks-2ba888

Just wondering if this is works as designed or an issue.

```
Example:
apiVersion: v1
kind: LimitRange
metadata:
  name: default-limit-range
  namespace: "{{ meta.name }}"
spec:
  limits:
  - default:
      cpu: 1
      memory: 512Mi
    defaultRequest:
      cpu: 0.5
      memory: 256Mi
    type: Container
```

When the above limitrange is set, and there is no node available with 0.5 CPU available; an endless amount of pods is spawned.

Since the limits are set on container level, the kubelet receives the requests, then the requestlimit is added and the container cannot be scheduled, the kubelet returns OutOfcpu and the replicaset deploys a new pod. And this starts an endless loop of pod spawning.

/sig scheduling
