### ISSUE TITLE
Consider linking to support resources from our github templates

### ISSUE THREAD

**Issue by castrojo** [kubernetes/community#5261]
![Ek9pr8jU0AEJ6YR](https://user-images.githubusercontent.com/1264109/96933752-0a436580-148f-11eb-8178-0610a43b2ced.jpg)

You can add links to external support resources in github templates, we should consider doing this so users end up in the right place.

**Comment by championshuttler** [comment]
@castrojo What are the resources I need to add, I want to take a stab ;)

**Comment by mrbobbytables** [comment]
@championshuttler It's been awhile, but we'd want to repalce the support GH issue template with a link to https://discuss.kubernetes.io 

Here is info on the GH template requirements:
https://docs.github.com/en/github/building-a-strong-community/configuring-issue-templates-for-your-repository#configuring-the-template-chooser

**Comment by mrbobbytables** [comment]
@championshuttler that doesn't actually fix it =/ I commented on the PR.
We want to **replace** the support issue templates in at least this repo and k/k with a link to discuss, something like this:
```

contact_links:
  - name: Support Request
    url: https://discuss.kubernetes.io  
    about: Support request or question relating to Kubernetes
```
