### ISSUE TITLE
SIG README formats are inconsistent and sometimes incomplete

### ISSUE THREAD

**Issue by jamiehannaford** [kubernetes/community#544]
Would it be possible to standardise a template for all SIGs to use in their READMEs? Something like:

```
# Title 

Mission statement

## Leads

## Contact us

## Meetings 

## Other links 
```

I'd be willing to take this on but wanted some feedback first.

**Comment by castrojo** [comment]
I'm wondering if a template would work? So instead of manually updating READMEs we could have one template with the appropriate metadata that could just autogenerate the READMEs for each SIG for consistency and drop them in the right directory. And then as a bonus also generate one-big-page to replace the list of SIGs (which are updated by hand) and also generate a one-line snippet for SIG leads to use as a topic in the slack channel. 

I've been in the situation before where a SIG meeting was listed differently in slack, on the SIG page, and the list-of-SIGs page, so perhaps thinking about a single source of truth for all the sig metadata and then autogenerating the rest would be worth investigating?

**Comment by jamiehannaford** [comment]
@castrojo I like that idea. Where would be best to store the SIG-specific info? Perhaps a JSON, YAML or MD file, like so?

```yaml
sigs:
  sig-openstack: 
     mission-statement: >
       This is the community page of the Kubernetes OpenStack SIG, a special interest group
       coordinating the cross-community efforts of the OpenStack and Kubernetes communities. 
     leads:
     - name: Foo 
       github: @foo
     - name: Bar
       email: contact@bar.com
     meetings:
     - day: monday
       utc: 0900
     - day: wednesday
       utc: 2100
     contact:
       slack: #sig-openstack
       mailing-list: ...
     other-links:
     - google.com
     - openstack.org
```
