### ISSUE TITLE
Template examples for MachineHealthCheck missing

### ISSUE THREAD

**Issue by cablunar** [kubernetes/community#6957]
### Describe the issue

The cluster-api-provider-aws should accomodate self healing kubeadmcontrolplane template examples, in the tempaltes folder.

Proposing to add the following code to `cluster-template-machinepool.yaml`, this enables kubeadmcontrolplanes to heal itself if an instance is taken down or otherwise unhealthy.
This is crutual information for at least production scenarios, where a clusters controlplane could be destroyed thought the aws console.

```yaml
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachineHealthCheck
metadata:
  name: "${CLUSTER_NAME}-kcp-unhealthy-5m"
spec:
  clusterName: "${CLUSTER_NAME}"
  maxUnhealthy: 100%
  selector:
    matchLabels:
      cluster.x-k8s.io/control-plane: ""
  unhealthyConditions:
    - type: Ready
      status: Unknown
      timeout: 300s
    - type: Ready
      status: "False"
      timeout: 300s
```
