### ISSUE TITLE
support folder mounts for config.d style directories

### ISSUE THREAD

**Issue by kbroughton** [kubernetes/community#818]
15:38 $ kubectl version
Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.5", GitCommit:"490c6f13df1cb6612e0993c4c14f2ff90f8cdbf3", GitTreeState:"clean", BuildDate:"2017-06-14T20:15:53Z", GoVersion:"go1.7.6", Compiler:"gc", Platform:"darwin/amd64"}

@jpeeler
Referring to  
https://github.com/kubernetes/community/blob/master/contributors/design-proposals/all-in-one-volume.md

I'd like to be able to create a container configMap like
```
/etc/telegraf/telegraf.conf
               /telegraf.d/input1.conf
                          /input2.conf
```

My configmaps are
telegraf> kubectl --namespace=kube-system create configmap telegraf-conf --from-file=telegraf.conf
telegraf> kubectl --namespace=kube-system create configmap telegraf-d --from-file=telegraf.d

projected type volumes gets me very close

It is possible to create the configMap contents with a directory but I see no way to place a file beside that mounted folder.
https://kubernetes.io/docs/tasks/configure-pod-container/configmap/

Here is my attempt
```
    apiVersion: extensions/v1beta1
    kind: Deployment
    metadata:
        name: telegraf
        namespace: kube-system
    spec:
      selector:
        matchLabels:
          k8s-mon: telegraf
    template:
      metadata:
        labels:
      spec:
        containers:
        - name: telegraf
          image: telegraf
          command: ['tail', '-f', '/dev/null']    # over-ride telegraf command to allow inspection
          volumeMounts:
            - name: telegraf
               mountPath: /etc/telegraf
###            - name: telegraf-d              # tried as both a single volumeMount and two nested ones
###               mountPath: /etc/telegraf/telegraf.d
      volumes:
      - name: telegraf
         projected:
           sources:
            - configMap:
                 name: telegraf-conf
                   items:
                   - key: telegraf.conf
                      path: telegraf.conf
            - configMap:
                 name: telegraf-d
#                items:
#                 - key: data
#                    path: telegraf.d
##                  - key: 10-redis.conf
##                   path: telegraf.d/10-wavefront.conf
##                - key: 20-prometheus.conf
##                    path: telegraf.d/20-prometheus.conf
```
Single '#' was another attempt to refer to the directory as the parent of the files, ie, 'data' in the spec.
Double '##' was attempting to ref keys in the config map by name.  This works if you remove the 
telegraf-conf configmap mounted at /etc/telegraf.

I also attempted constructing the configmap like so
kubectl --namespace=kube-system create configmap teltest --from-file=telegraf.conf --from-file=telegraf.d

but configmap flattens the contents of telegraf.d to the same level as telegraf.conf

And I tried giving a keyName to the directory
kubectl --namespace=kube-system create configmap teltest2 --from-file=telegrafconf=telegraf.d
error: cannot give a key name for a directory path.

The relevant output from 
```
> kubectl --namespace=kube-system describe deploy/telegraf

      Mounts:
        /etc/telegraf from telegraf (rw)
        /etc/telegraf/telegraf.d from telegraf-d (rw)
    Volumes:
     telegraf:
    <unknown>
     telegraf-d:
    <unknown>
```
But inside the container, only the /etc/telegraf/telegraf.conf is mounted (no errors afaik)

There doesn't seem to be a way to place a file beside a dir in a projected volume which is required to support standard unix conf.d configurations.  The workaround for now is the entrypoint script copying a file from /etc/telegraf/telegraf.d/telegraf.conf to /etc/telegraf/telegraf.conf
